language: php

php:
  - 5.3
  - 5.4

branches:
  only:
    - master

before_script:
  - curl http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: 
    - if [ $(phpenv version-name) = "5.4" ]; then bin/dspec && bin/behat -fprogress; fi
    - if [ $(phpenv version-name) = "5.3" ]; then bin/behat -fprogress --tags="~@php5.4"; fi
